"""Turn a stored report version (blocks + citations) into Markdown / HTML / PDF / DOCX.

Citation markers `[[c:N]]` become superscript `[N]` in prose and are listed as
numbered sources at the end.
"""

from __future__ import annotations

import io
import re
from html import escape

_MARKER = re.compile(r"\[\[c:(\d+)\]\]")


def _md_inline(text: str) -> str:
    return _MARKER.sub(r"[\1]", text or "")


def blocks_to_markdown(blocks: list[dict], citations: list[dict]) -> str:
    out: list[str] = []
    for b in blocks:
        t = b.get("type")
        if t == "heading":
            out.append(f"{'#' * int(b.get('level', 2))} {_md_inline(b.get('text', ''))}")
        elif t == "paragraph":
            out.append(_md_inline(b.get("text", "")))
        elif t == "kv":
            for it in b.get("items", []):
                out.append(f"- **{it.get('label', '')}:** {_md_inline(str(it.get('value', '')))}")
        elif t == "table":
            cols = b.get("columns", [])
            out.append("| " + " | ".join(cols) + " |")
            out.append("| " + " | ".join("---" for _ in cols) + " |")
            for row in b.get("rows", []):
                out.append("| " + " | ".join(_md_inline(str(c)) for c in row) + " |")
        out.append("")
    if citations:
        out.append("---\n\n**Sources**\n")
        for c in citations:
            loc = c.get("document_filename") or c.get("document_id") or "source"
            page = f", p.{c['page_no']}" if c.get("page_no") else ""
            conf = f" — confidence {c['confidence']:.2f}" if c.get("confidence") is not None else ""
            out.append(f"[{c['marker']}] {loc}{page} — “{(c.get('snippet') or '').strip()}”{conf}")
    return "\n".join(out).strip() + "\n"


def _html_inline(text: str) -> str:
    return _MARKER.sub(r'<sup class="cite">[\1]</sup>', escape(text or ""))


def render_html(version: dict, *, report_title: str = "") -> str:
    blocks = version.get("blocks", [])
    citations = version.get("citations", [])
    parts: list[str] = []
    for b in blocks:
        t = b.get("type")
        if t == "heading":
            lvl = min(4, max(1, int(b.get("level", 2))))
            parts.append(f"<h{lvl}>{_html_inline(b.get('text', ''))}</h{lvl}>")
        elif t == "paragraph":
            parts.append(f"<p>{_html_inline(b.get('text', ''))}</p>")
        elif t == "kv":
            rows = "".join(
                f"<tr><th>{escape(str(it.get('label', '')))}</th>"
                f"<td>{_html_inline(str(it.get('value', '')))}</td></tr>"
                for it in b.get("items", [])
            )
            parts.append(f'<table class="kv">{rows}</table>')
        elif t == "table":
            head = "".join(f"<th>{escape(str(c))}</th>" for c in b.get("columns", []))
            body = "".join(
                "<tr>" + "".join(f"<td>{_html_inline(str(c))}</td>" for c in row) + "</tr>"
                for row in b.get("rows", [])
            )
            parts.append(
                f'<table class="grid"><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>'
            )

    if citations:
        items = "".join(
            f"<li>{escape(c.get('document_filename') or c.get('document_id') or 'source')}"
            + (f", p.{c['page_no']}" if c.get("page_no") else "")
            + (f" &mdash; &ldquo;{escape((c.get('snippet') or '').strip())}&rdquo;")
            + (
                f" &mdash; confidence {c['confidence']:.2f}"
                if c.get("confidence") is not None
                else ""
            )
            + "</li>"
            for c in citations
        )
        parts.append(f'<h3>Sources</h3><ol class="sources">{items}</ol>')

    title = escape(report_title or version.get("title") or "CoalMind Report")
    css = """
      body { font-family: 'Helvetica','Arial',sans-serif; color:#111; font-size:11pt; }
      h1 { font-size:16pt; } h2 { font-size:13pt; } h3 { font-size:11pt; }
      table { border-collapse:collapse; width:100%; margin:8px 0; }
      table.grid th, table.grid td { border:1px solid #999; padding:4px 6px; text-align:left; }
      table.kv th { text-align:left; padding:2px 8px 2px 0; color:#555; width:180px; }
      table.kv th, table.kv td { vertical-align:top; }
      table.kv td { padding:2px 0; }
      sup.cite { color:#1d4ed8; font-size:8pt; }
      ol.sources li { margin:3px 0; font-size:9pt; color:#333; }
      .footer { margin-top:24px; font-size:8pt; color:#777; }
    """
    return (
        f"<!doctype html><html><head><meta charset='utf-8'><title>{title}</title>"
        f"<style>{css}</style></head><body>{''.join(parts)}"
        f"<div class='footer'>Generated by CoalMind AI — draft for officer review and signature. "
        f"SIH 2026 · PS 26023.</div></body></html>"
    )


def to_pdf(html: str) -> bytes:
    from xhtml2pdf import pisa

    buf = io.BytesIO()
    result = pisa.CreatePDF(src=html, dest=buf, encoding="utf-8")
    if result.err:
        raise RuntimeError("PDF generation failed")
    return buf.getvalue()


def to_docx(version: dict, *, report_title: str = "") -> bytes:
    from docx import Document as Docx
    from docx.shared import Pt

    doc = Docx()
    doc.add_heading(report_title or version.get("title") or "CoalMind Report", level=0)

    for b in version.get("blocks", []):
        t = b.get("type")
        if t == "heading":
            doc.add_heading(
                _MARKER.sub(r"[\1]", b.get("text", "")), level=min(4, int(b.get("level", 2)))
            )
        elif t == "paragraph":
            doc.add_paragraph(_MARKER.sub(r"[\1]", b.get("text", "")))
        elif t == "kv":
            tbl = doc.add_table(rows=0, cols=2)
            for it in b.get("items", []):
                r = tbl.add_row().cells
                r[0].text = str(it.get("label", ""))
                r[1].text = _MARKER.sub(r"[\1]", str(it.get("value", "")))
        elif t == "table":
            cols = b.get("columns", [])
            tbl = doc.add_table(rows=1, cols=len(cols))
            for i, c in enumerate(cols):
                tbl.rows[0].cells[i].text = str(c)
            for row in b.get("rows", []):
                cells = tbl.add_row().cells
                for i, c in enumerate(row):
                    cells[i].text = _MARKER.sub(r"[\1]", str(c))

    cits = version.get("citations", [])
    if cits:
        doc.add_heading("Sources", level=2)
        for c in cits:
            loc = c.get("document_filename") or c.get("document_id") or "source"
            page = f", p.{c['page_no']}" if c.get("page_no") else ""
            p = doc.add_paragraph(
                f"[{c['marker']}] {loc}{page} — “{(c.get('snippet') or '').strip()}”"
            )
            p.runs[0].font.size = Pt(8)

    foot = doc.add_paragraph("Generated by CoalMind AI — draft for officer review and signature.")
    foot.runs[0].font.size = Pt(8)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
